// Code generated by oapi-codegen. DO NOT EDIT.

package xgoname

type Client struct {
	Name string   `json:"name" validate:"required"`
	ID   *float32 `json:"id,omitempty"`
}

type ClientRenamedByExtension struct {
	Name              string   `json:"name" validate:"required"`
	AccountIdentifier *float32 `json:"id,omitempty"`
}
