// Code generated by oapi-codegen. DO NOT EDIT.

package xgoname

import (
	"github.com/go-playground/validator/v10"
)

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type Client struct {
	Name string   `json:"name" validate:"required"`
	ID   *float32 `json:"id,omitempty"`
}

type ClientRenamedByExtension struct {
	Name              string   `json:"name" validate:"required"`
	AccountIdentifier *float32 `json:"id,omitempty"`
}
