// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type SpecificIssueCode string

const (
	BUSINESSERROR  SpecificIssueCode = "BUSINESS_ERROR"
	INVALIDREQUEST SpecificIssueCode = "INVALID_REQUEST"
)

// validSpecificIssueCodeValues is a map of valid values for SpecificIssueCode
var validSpecificIssueCodeValues = map[SpecificIssueCode]bool{
	BUSINESSERROR:  true,
	INVALIDREQUEST: true,
}

// Validate checks if the SpecificIssueCode value is valid
func (s SpecificIssueCode) Validate() error {
	if !validSpecificIssueCodeValues[s] {
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid SpecificIssueCode value, got: %v", s))
	}
	return nil
}

var bodyTypesValidate *validator.Validate

func init() {
	bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(bodyTypesValidate)
}

type TestEndpointBody = CombinedError

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type BaseError struct {
	Name    *string       `json:"name,omitempty"`
	Message *string       `json:"message,omitempty"`
	Issues  []ErrorDetail `json:"issues,omitempty"`
}

type ErrorDetail struct {
	Field *string `json:"field,omitempty"`
	Issue *string `json:"issue,omitempty"`
}

type SpecificError struct {
	Issues []SpecificIssue `json:"issues,omitempty"`
}

type SpecificIssue struct {
	Code        *SpecificIssueCode `json:"code,omitempty"`
	Description *string            `json:"description,omitempty"`
	Field       *string            `json:"field,omitempty"`
}

func (s SpecificIssue) Validate() error {
	var errors runtime.ValidationErrors
	if s.Code != nil {
		if v, ok := any(s.Code).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Code", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type CombinedError struct {
	Name    *string         `json:"name,omitempty"`
	Message *string         `json:"message,omitempty"`
	Issues  []SpecificIssue `json:"issues,omitempty"`
}
