// Code generated by oapi-codegen. DO NOT EDIT.

package defaultsint64type

type GetClientResponse struct {
	ID  *int64 `json:"id,omitempty"`
	Age *int32 `json:"age,omitempty"`
}

type Person struct {
	ID  *int64 `json:"id,omitempty"`
	Age *int32 `json:"age,omitempty"`
}
