// Code generated by oapi-codegen. DO NOT EDIT.

package defaultsint64type

import (
	"github.com/go-playground/validator/v10"
	"github.com/uptrace/oapi-codegen-dd/v3/pkg/runtime"
)

type GetClientResponse = Person

type Person struct {
	ID  *int64 `json:"id,omitempty"`
	Age *int32 `json:"age,omitempty"`
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
