// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type ProcessPaymentErrorResponseText string

const (
	ProcessPaymentErrorResponseTextInternalServerError ProcessPaymentErrorResponseText = "Internal Server Error"
)

// validProcessPaymentErrorResponseTextValues is a map of valid values for ProcessPaymentErrorResponseText
var validProcessPaymentErrorResponseTextValues = map[ProcessPaymentErrorResponseText]bool{
	ProcessPaymentErrorResponseTextInternalServerError: true,
}

// Validate checks if the ProcessPaymentErrorResponseText value is valid
func (p ProcessPaymentErrorResponseText) Validate() error {
	if !validProcessPaymentErrorResponseTextValues[p] {
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid ProcessPaymentErrorResponseText value, got: %v", p))
	}
	return nil
}

type ProcessPaymentErrorResponse string

const (
	ProcessPaymentErrorResponseInternalServerError ProcessPaymentErrorResponse = "Internal Server Error"
)

// validProcessPaymentErrorResponseValues is a map of valid values for ProcessPaymentErrorResponse
var validProcessPaymentErrorResponseValues = map[ProcessPaymentErrorResponse]bool{
	ProcessPaymentErrorResponseInternalServerError: true,
}

// Validate checks if the ProcessPaymentErrorResponse value is valid
func (p ProcessPaymentErrorResponse) Validate() error {
	if !validProcessPaymentErrorResponseValues[p] {
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid ProcessPaymentErrorResponse value, got: %v", p))
	}
	return nil
}

var bodyTypesValidate *validator.Validate

func init() {
	bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(bodyTypesValidate)
}

type ProcessPaymentBody = map[string]any
