// Code generated by oapi-codegen. DO NOT EDIT.

package xgotype

import (
	googleuuid "github.com/google/uuid"
)

type Client struct {
	Name string   `json:"name" validate:"required"`
	ID   *float32 `json:"id,omitempty"`
}

type ClientWithExtension struct {
	Name googleuuid.UUID `json:"name" validate:"required"`
	ID   *int64          `json:"id,omitempty"`
}
