// Code generated by oapi-codegen. DO NOT EDIT.

package union

import (
	"bytes"
	"encoding/json"
	"fmt"

	"github.com/doordash-oss/oapi-codegen-dd/v3/pkg/runtime"
)

type ListTargetsResponse = TargetsResponse

type TargetsResponse struct {
	Targets []Target `json:"targets,omitempty"`
}

type Target struct {
	TargetBase           TargetBase        `json:"-"`
	Target_AllOf1        *Target_AllOf1    `json:"-"`
	AdditionalProperties map[string]string `json:"-"`
}

// Getter for additional properties for Target. Returns the specified
// element and whether it was found
func (t Target) Get(fieldName string) (value string, found bool) {
	if t.AdditionalProperties != nil {
		value, found = t.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Target
func (t *Target) Set(fieldName string, value string) {
	if t.AdditionalProperties == nil {
		t.AdditionalProperties = make(map[string]string)
	}
	t.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Target to handle AdditionalProperties
func (t *Target) UnmarshalJSON(data []byte) error {
	object := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &object); err != nil {
		return err
	}

	if err := json.Unmarshal(data, &t.TargetBase); err != nil {
		return fmt.Errorf("error reading embedded 'TargetBase': %w", err)
	}
	delete(object, "id")
	delete(object, "type")
	if err := json.Unmarshal(data, &t.Target_AllOf1); err != nil {
		return fmt.Errorf("error reading embedded 'Target_AllOf1': %w", err)
	}
	delete(object, "email")
	delete(object, "url")

	if len(object) != 0 {
		t.AdditionalProperties = make(map[string]string)
		for fieldName, fieldBuf := range object {
			var fieldVal string
			if err := json.Unmarshal(fieldBuf, &fieldVal); err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			t.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Target to handle AdditionalProperties
func (t Target) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	{
		embeddedJSON, err := json.Marshal(t.TargetBase)
		if err != nil {
			return nil, fmt.Errorf("error marshaling embedded 'TargetBase': %w", err)
		}
		var embeddedObj map[string]json.RawMessage
		if err := json.Unmarshal(embeddedJSON, &embeddedObj); err == nil {
			for k, v := range embeddedObj {
				object[k] = v
			}
		}
	}

	if t.Target_AllOf1 != nil {
		{
			embeddedJSON, err := json.Marshal(t.Target_AllOf1)
			if err != nil {
				return nil, fmt.Errorf("error marshaling embedded 'Target_AllOf1': %w", err)
			}
			var embeddedObj map[string]json.RawMessage
			if err := json.Unmarshal(embeddedJSON, &embeddedObj); err == nil {
				for k, v := range embeddedObj {
					object[k] = v
				}
			}
		}
	}

	for fieldName, field := range t.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

type TargetBase struct {
	ID   int    `json:"id"`
	Type string `json:"type"`
}

type EmailTarget struct {
	Email string `json:"email"`
}

type WebhookTarget struct {
	URL string `json:"url"`
}

type Target_AllOf1 struct {
	Target_AllOf1_AnyOf *Target_AllOf1_AnyOf `json:"-"`
}

func (t Target_AllOf1) MarshalJSON() ([]byte, error) {
	var parts []json.RawMessage

	{
		b, err := runtime.MarshalJSON(t.Target_AllOf1_AnyOf)
		if err != nil {
			return nil, fmt.Errorf("Target_AllOf1_AnyOf marshal: %w", err)
		}
		parts = append(parts, b)
	}

	return runtime.CoalesceOrMerge(parts...)
}

func (t *Target_AllOf1) UnmarshalJSON(data []byte) error {
	trim := bytes.TrimSpace(data)
	if bytes.Equal(trim, []byte("null")) {
		return nil
	}
	if len(trim) == 0 {
		return fmt.Errorf("empty JSON input")
	}

	if t.Target_AllOf1_AnyOf == nil {
		t.Target_AllOf1_AnyOf = &Target_AllOf1_AnyOf{}
	}

	if err := runtime.UnmarshalJSON(data, t.Target_AllOf1_AnyOf); err != nil {
		return fmt.Errorf("Target_AllOf1_AnyOf unmarshal: %w", err)
	}

	return nil
}

func UnmarshalAs[T any](v json.RawMessage) (T, error) {
	var res T
	err := json.Unmarshal(v, &res)
	return res, err
}

func marshalJSONWithDiscriminator(data []byte, field, value string) ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)
	if data != nil {
		if err := json.Unmarshal(data, &object); err != nil {
			return nil, err
		}
	}

	object[field], err = json.Marshal(value)
	if err != nil {
		return nil, fmt.Errorf("error marshaling discriminator field '%s': %w", field, err)
	}

	return json.Marshal(object)
}

type Target_AllOf1_AnyOf struct {
	runtime.Either[EmailTarget, WebhookTarget]
}

func (t *Target_AllOf1_AnyOf) Validate() error {
	if t.IsA() {
		if v, ok := any(t.A).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	if t.IsB() {
		if v, ok := any(t.B).(runtime.Validator); ok {
			return v.Validate()
		}
	}
	return nil
}
