// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type OrderDirection string

const (
	OrderDirectionAsc  OrderDirection = "asc"
	OrderDirectionDesc OrderDirection = "desc"
)

// validOrderDirectionValues is a map of valid values for OrderDirection
var validOrderDirectionValues = map[OrderDirection]bool{
	OrderDirectionAsc:  true,
	OrderDirectionDesc: true,
}

// Validate checks if the OrderDirection value is valid
func (o OrderDirection) Validate() error {
	if !validOrderDirectionValues[o] {
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid OrderDirection value, got: %v", o))
	}
	return nil
}

type Priority string

const (
	PriorityHigh   Priority = "high"
	PriorityLow    Priority = "low"
	PriorityMedium Priority = "medium"
)

// validPriorityValues is a map of valid values for Priority
var validPriorityValues = map[Priority]bool{
	PriorityHigh:   true,
	PriorityLow:    true,
	PriorityMedium: true,
}

// Validate checks if the Priority value is valid
func (p Priority) Validate() error {
	if !validPriorityValues[p] {
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid Priority value, got: %v", p))
	}
	return nil
}

type StatusCode int

const (
	StatusCodeN200 StatusCode = 200
	StatusCodeN404 StatusCode = 404
	StatusCodeN500 StatusCode = 500
)

// validStatusCodeValues is a map of valid values for StatusCode
var validStatusCodeValues = map[StatusCode]bool{
	StatusCodeN200: true,
	StatusCodeN404: true,
	StatusCodeN500: true,
}

// Validate checks if the StatusCode value is valid
func (s StatusCode) Validate() error {
	if !validStatusCodeValues[s] {
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid StatusCode value, got: %v", s))
	}
	return nil
}

type Color string

const (
	ColorBlue  Color = "blue"
	ColorGreen Color = "green"
	ColorRed   Color = "red"
)

// validColorValues is a map of valid values for Color
var validColorValues = map[Color]bool{
	ColorBlue:  true,
	ColorGreen: true,
	ColorRed:   true,
}

// Validate checks if the Color value is valid
func (c Color) Validate() error {
	if !validColorValues[c] {
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid Color value, got: %v", c))
	}
	return nil
}

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type TestObject struct {
	OrderDirection *OrderDirection `json:"orderDirection,omitempty"`
	Priority       *Priority       `json:"priority,omitempty"`
	StatusCode     *StatusCode     `json:"statusCode,omitempty"`
	Color          *Color          `json:"color,omitempty"`
}

func (t TestObject) Validate() error {
	var errors runtime.ValidationErrors
	if t.OrderDirection != nil {
		if v, ok := any(t.OrderDirection).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("OrderDirection", err)
			}
		}
	}
	if t.Priority != nil {
		if v, ok := any(t.Priority).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Priority", err)
			}
		}
	}
	if t.StatusCode != nil {
		if v, ok := any(t.StatusCode).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("StatusCode", err)
			}
		}
	}
	if t.Color != nil {
		if v, ok := any(t.Color).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Color", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}
