// Code generated by oapi-codegen. DO NOT EDIT.

package xgotypename

type Client struct {
	Name string   `json:"name" validate:"required"`
	ID   *float32 `json:"id,omitempty"`
}

type ClientWithExtension = ClientRenamedByExtension

type ClientRenamedByExtension struct {
	Name string   `json:"name" validate:"required"`
	ID   *float32 `json:"id,omitempty"`
}
