// Code generated by oapi-codegen. DO NOT EDIT.

package customclienttype

import (
	"github.com/go-playground/validator/v10"
)

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type Client struct {
	Name string `json:"name" validate:"required"`
}
