// Code generated by oapi-codegen. DO NOT EDIT.

package client

type ClientType struct {
	Name string          `json:"name" validate:"required"`
	Type *ClientTypeType `json:"type,omitempty"`
}

type Error struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (s Error) Error() string {
	res0 := s.Message
	if res0 == nil {
		return "unknown error"
	}
	res1 := *res0
	return res1
}
