// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

type GetFooResponse = map[string]any

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type Order struct {
	Client  *Order_Client `json:"client,omitempty"`
	Address *string       `json:"address,omitempty"`
}

func (o Order) Validate() error {
	var errors runtime.ValidationErrors
	if o.Client != nil {
		if v, ok := any(o.Client).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Client", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Order_Client struct {
	Same     *int    `json:"same,omitempty"`
	Issuer   string  `json:"issuer" validate:"required"`
	Verifier *string `json:"verifier,omitempty"`
}

func (o Order_Client) Validate() error {
	if err := schemaTypesValidate.Struct(o); err != nil {
		return runtime.ConvertValidatorError(err)
	}
	return nil
}

type Identity struct {
	Same   *string `json:"same,omitempty"`
	Issuer string  `json:"issuer" validate:"required"`
}

func (i Identity) Validate() error {
	if err := schemaTypesValidate.Struct(i); err != nil {
		return runtime.ConvertValidatorError(err)
	}
	return nil
}

type Verification struct {
	Same     *int    `json:"same,omitempty"`
	Verifier *string `json:"verifier,omitempty"`
}
