// Code generated by oapi-codegen. DO NOT EDIT.

package multipleresponses

import (
	"github.com/google/uuid"
)

type CreateBookingResponse struct {
	ID            *uuid.UUID `json:"id,omitempty"`
	TripID        *uuid.UUID `json:"trip_id,omitempty"`
	PassengerName *string    `json:"passenger_name,omitempty"`
	HasBicycle    *bool      `json:"has_bicycle,omitempty"`
	HasDog        *bool      `json:"has_dog,omitempty"`
	Links         *LinksSelf `json:"links,omitempty"`
}

type CreateBookingErrorResponse = BadRequest

type BadRequest = Problem

type Conflict = Problem

type InternalServerError = Problem

type NotFound = Problem

type TooManyRequests = Problem

type Unauthorized = Problem
