// Code generated by oapi-codegen. DO NOT EDIT.

package multipleresponses

import (
	"github.com/google/uuid"
)

type LinksSelf struct {
	Self *string `json:"self,omitempty"`
}

type Problem struct {
	Type     *string `json:"type,omitempty"`
	Title    *string `json:"title,omitempty"`
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   *int    `json:"status,omitempty"`
}

func (s Problem) Error() string {
	return "unmapped client error"
}

type Booking struct {
	ID            *uuid.UUID `json:"id,omitempty"`
	TripID        *uuid.UUID `json:"trip_id,omitempty"`
	PassengerName *string    `json:"passenger_name,omitempty"`
	HasBicycle    *bool      `json:"has_bicycle,omitempty"`
	HasDog        *bool      `json:"has_dog,omitempty"`
}
