// Code generated by oapi-codegen. DO NOT EDIT.

package xomitempty

type Client struct {
	Name string   `json:"name" validate:"required"`
	ID   *float32 `json:"id,omitempty"`
}

type ClientWithExtension struct {
	Name string   `json:"name,omitempty" validate:"required"`
	ID   *float32 `json:"id,omitempty"`
}
