// Copyright 2025 DoorDash, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.

package codegen

import (
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestConfiguration_WithDefaults(t *testing.T) {
	t.Run("empty config gets defaults", func(t *testing.T) {
		empty := Configuration{}

		result := empty.WithDefaults()

		assert.Equal(t, "gen", result.PackageName)
		assert.Equal(t, "Code generated by oapi-codegen. DO NOT EDIT.", result.CopyrightHeader)
		require.NotNil(t, result.Generate)
		assert.Equal(t, "int", result.Generate.DefaultIntType)

		// AlwaysPrefixEnumValues defaults to false (allows user override)
		assert.False(t, result.Generate.AlwaysPrefixEnumValues)

		require.NotNil(t, result.Client)
		assert.Equal(t, "Client", result.Client.Name)
		assert.Equal(t, 3*time.Second, result.Client.Timeout)

		require.NotNil(t, result.Output)
		// Boolean defaults are not applied when Output is nil - entire struct is copied
		assert.True(t, result.Output.UseSingleFile)
		assert.Equal(t, "gen.go", result.Output.Filename)
	})

	t.Run("user config takes priority over defaults", func(t *testing.T) {
		userConfig := Configuration{
			PackageName:     "mypackage",
			CopyrightHeader: "My Copyright",
			Generate: &GenerateOptions{
				Client:         true,
				DefaultIntType: "int64",
			},
		}

		result := userConfig.WithDefaults()

		assert.Equal(t, "mypackage", result.PackageName)
		assert.Equal(t, "My Copyright", result.CopyrightHeader)
		assert.True(t, result.Generate.Client)
		assert.Equal(t, "int64", result.Generate.DefaultIntType)
		// AlwaysPrefixEnumValues is not defaulted when Generate is provided by user
		// (we can't distinguish "not set" from "set to false")
		assert.False(t, result.Generate.AlwaysPrefixEnumValues)
	})

	t.Run("partial user config fills gaps from defaults", func(t *testing.T) {
		userConfig := Configuration{
			PackageName: "mypackage",
			// No Generate, Client, or Output specified
		}

		result := userConfig.WithDefaults()

		assert.Equal(t, "mypackage", result.PackageName)
		assert.Equal(t, "Code generated by oapi-codegen. DO NOT EDIT.", result.CopyrightHeader)
		require.NotNil(t, result.Generate)
		assert.Equal(t, "int", result.Generate.DefaultIntType)
		require.NotNil(t, result.Client)
		assert.Equal(t, "Client", result.Client.Name)
	})

	t.Run("user Filter config is preserved", func(t *testing.T) {
		userConfig := Configuration{
			Filter: FilterConfig{
				Include: FilterParamsConfig{
					Paths: []string{"/api/v1"},
				},
			},
		}

		result := userConfig.WithDefaults()
		assert.Equal(t, []string{"/api/v1"}, result.Filter.Include.Paths)
	})

	t.Run("user AdditionalImports are preserved", func(t *testing.T) {
		userConfig := Configuration{
			AdditionalImports: []AdditionalImport{
				{Package: "github.com/example/pkg"},
			},
		}

		result := userConfig.WithDefaults()
		require.Len(t, result.AdditionalImports, 1)
		assert.Equal(t, "github.com/example/pkg", result.AdditionalImports[0].Package)
	})

	t.Run("user ErrorMapping is preserved", func(t *testing.T) {
		userConfig := Configuration{
			ErrorMapping: map[string]string{
				"Error": "message",
			},
		}

		result := userConfig.WithDefaults()
		assert.Equal(t, "message", result.ErrorMapping["Error"])
	})

	t.Run("partial Output fills from defaults", func(t *testing.T) {
		userConfig := Configuration{
			Output: &Output{
				Directory: "/custom/dir",
			},
		}

		result := userConfig.WithDefaults()
		assert.Equal(t, "/custom/dir", result.Output.Directory)
		assert.Equal(t, "gen.go", result.Output.Filename) // filename filled from defaults
		assert.False(t, result.Output.UseSingleFile)      // boolean not filled from defaults
	})

	t.Run("partial Client fills from defaults", func(t *testing.T) {
		userConfig := Configuration{
			Client: &Client{
				Name: "MyClient",
			},
		}

		result := userConfig.WithDefaults()
		assert.Equal(t, "MyClient", result.Client.Name)
		assert.Equal(t, 3*time.Second, result.Client.Timeout) // from defaults
	})

	t.Run("user UserTemplates are preserved", func(t *testing.T) {
		userConfig := Configuration{
			UserTemplates: map[string]string{
				"custom": "template",
			},
		}

		result := userConfig.WithDefaults()
		assert.Equal(t, "template", result.UserTemplates["custom"])
	})

	t.Run("user UserContext is preserved", func(t *testing.T) {
		userConfig := Configuration{
			UserContext: map[string]any{
				"key": "value",
			},
		}

		result := userConfig.WithDefaults()
		assert.Equal(t, "value", result.UserContext["key"])
	})
}

func TestConfiguration_OverwriteWith(t *testing.T) {
	t.Run("empty other does not overwrite", func(t *testing.T) {
		userConfig := Configuration{
			PackageName:     "mypackage",
			CopyrightHeader: "My Copyright",
		}
		empty := Configuration{}

		result := userConfig.OverwriteWith(empty)

		assert.Equal(t, "mypackage", result.PackageName)
		assert.Equal(t, "My Copyright", result.CopyrightHeader)
	})

	t.Run("other overwrites user config", func(t *testing.T) {
		userConfig := Configuration{
			PackageName:     "mypackage",
			CopyrightHeader: "My Copyright",
		}
		overrides := Configuration{
			PackageName: "overridden",
		}

		result := userConfig.OverwriteWith(overrides)

		assert.Equal(t, "overridden", result.PackageName)
		assert.Equal(t, "My Copyright", result.CopyrightHeader) // not overwritten
	})

	t.Run("other Filter overwrites user Filter", func(t *testing.T) {
		userConfig := Configuration{
			Filter: FilterConfig{
				Include: FilterParamsConfig{
					Paths: []string{"/user/path"},
				},
			},
		}
		overrides := Configuration{
			Filter: FilterConfig{
				Include: FilterParamsConfig{
					Paths: []string{"/override/path"},
				},
			},
		}

		result := userConfig.OverwriteWith(overrides)
		assert.Equal(t, []string{"/override/path"}, result.Filter.Include.Paths)
	})

	t.Run("other Output fields overwrite user Output fields", func(t *testing.T) {
		userConfig := Configuration{
			Output: &Output{
				Directory: "/user/dir",
				Filename:  "user.go",
			},
		}
		overrides := Configuration{
			Output: &Output{
				Directory: "/override/dir",
			},
		}

		result := userConfig.OverwriteWith(overrides)
		assert.Equal(t, "/override/dir", result.Output.Directory)
		assert.Equal(t, "user.go", result.Output.Filename) // not overwritten
	})

	t.Run("other Generate fields overwrite user Generate fields", func(t *testing.T) {
		userConfig := Configuration{
			Generate: &GenerateOptions{
				Client:         true,
				DefaultIntType: "int32",
			},
		}
		overrides := Configuration{
			Generate: &GenerateOptions{
				DefaultIntType: "int64",
			},
		}

		result := userConfig.OverwriteWith(overrides)
		assert.True(t, result.Generate.Client)                   // not overwritten
		assert.Equal(t, "int64", result.Generate.DefaultIntType) // overwritten
	})

	t.Run("other Client fields overwrite user Client fields", func(t *testing.T) {
		userConfig := Configuration{
			Client: &Client{
				Name:    "UserClient",
				Timeout: 5 * time.Second,
			},
		}
		overrides := Configuration{
			Client: &Client{
				Timeout: 10 * time.Second,
			},
		}

		result := userConfig.OverwriteWith(overrides)
		assert.Equal(t, "UserClient", result.Client.Name)      // not overwritten
		assert.Equal(t, 10*time.Second, result.Client.Timeout) // overwritten
	})

	t.Run("other AdditionalImports overwrite user AdditionalImports", func(t *testing.T) {
		userConfig := Configuration{
			AdditionalImports: []AdditionalImport{
				{Package: "github.com/user/pkg"},
			},
		}
		overrides := Configuration{
			AdditionalImports: []AdditionalImport{
				{Package: "github.com/override/pkg"},
			},
		}

		result := userConfig.OverwriteWith(overrides)
		require.Len(t, result.AdditionalImports, 1)
		assert.Equal(t, "github.com/override/pkg", result.AdditionalImports[0].Package)
	})

	t.Run("other ErrorMapping overwrites user ErrorMapping", func(t *testing.T) {
		userConfig := Configuration{
			ErrorMapping: map[string]string{
				"Error": "user_message",
			},
		}
		overrides := Configuration{
			ErrorMapping: map[string]string{
				"Error": "override_message",
			},
		}

		result := userConfig.OverwriteWith(overrides)
		assert.Equal(t, "override_message", result.ErrorMapping["Error"])
	})

	t.Run("SkipPrune can be overwritten", func(t *testing.T) {
		userConfig := Configuration{
			SkipPrune: false,
		}
		overrides := Configuration{
			SkipPrune: true,
		}

		result := userConfig.OverwriteWith(overrides)
		assert.True(t, result.SkipPrune)
	})
}

// TestConfiguration_Merge tests backwards compatibility
func TestConfiguration_Merge(t *testing.T) {
	t.Run("Merge calls WithDefaults for backwards compatibility", func(t *testing.T) {
		userConfig := Configuration{
			PackageName: "mypackage",
		}

		result := userConfig.Merge(Configuration{})

		// Should get defaults
		assert.Equal(t, "mypackage", result.PackageName)
		assert.Equal(t, "Code generated by oapi-codegen. DO NOT EDIT.", result.CopyrightHeader)
		require.NotNil(t, result.Generate)
		assert.Equal(t, "int", result.Generate.DefaultIntType)
		require.NotNil(t, result.Client)
		assert.Equal(t, "Client", result.Client.Name)
	})
}
