// Code generated by oapi-codegen. DO NOT EDIT.

package slicespointer

import (
	"github.com/go-playground/validator/v10"
)

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type Payments []string

type Data map[string]any

type User struct {
	Payments Payments       `json:"payments,omitempty"`
	Data     Data           `json:"data,omitempty"`
	Prefs    []string       `json:"prefs,omitempty"`
	Address  map[string]any `json:"address,omitempty"`
}
