// Code generated by oapi-codegen. DO NOT EDIT.

package example2

import (
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
)

type ClientTypeType string

const (
	Company    ClientTypeType = "company"
	Individual ClientTypeType = "individual"
)

// validClientTypeTypeValues is a map of valid values for ClientTypeType
var validClientTypeTypeValues = map[ClientTypeType]bool{
	Company:    true,
	Individual: true,
}

// Validate checks if the ClientTypeType value is valid
func (c ClientTypeType) Validate() error {
	if !validClientTypeTypeValues[c] {
		return runtime.ValidationErrors{}.Add("Enum", fmt.Sprintf("must be a valid ClientTypeType value, got: %v", c))
	}
	return nil
}
