// Code generated by oapi-codegen. DO NOT EDIT.

package example2

import (
	"github.com/go-playground/validator/v10"
)

var bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type CreateOrderBody struct {
	UserID     *string     `form:"user_id,omitempty" json:"user_id,omitempty" url:"user_id,omitempty"`
	ClientType *ClientType `form:"client_type,omitempty" json:"client_type,omitempty" url:"client_type,omitempty"`
}
