// Code generated by oapi-codegen. DO NOT EDIT.

package example2

import (
	"github.com/go-playground/validator/v10"
)

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type ClientType struct {
	Name    string          `json:"name" validate:"required"`
	Address *Address        `json:"address,omitempty"`
	Type    *ClientTypeType `json:"type,omitempty"`
}

type Address struct {
	Street string `json:"street" validate:"required"`
	City   string `json:"city" validate:"required"`
	Zip    string `json:"zip" validate:"required"`
}
