// Code generated by oapi-codegen. DO NOT EDIT.

package client

type GetClientResponse struct {
	Name string `json:"name" validate:"required"`
}

type UpdateClientErrorResponse struct {
	Code string `json:"code" validate:"required"`
}

func (r UpdateClientErrorResponse) Error() string {
	res := r.Code
	return res
}
