// Code generated by oapi-codegen. DO NOT EDIT.

package advanced

import (
	"time"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var pathTypesValidate *validator.Validate

func init() {
	pathTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(pathTypesValidate)
}

type GetUserPath struct {
	ID string `json:"id" validate:"required"`
}

func (g GetUserPath) Validate() error {
	if err := pathTypesValidate.Struct(g); err != nil {
		return runtime.ConvertValidatorError(err)
	}
	return nil
}

type UpdateUserPath struct {
	ID string `json:"id" validate:"required"`
}

func (u UpdateUserPath) Validate() error {
	if err := pathTypesValidate.Struct(u); err != nil {
		return runtime.ConvertValidatorError(err)
	}
	return nil
}

var bodyTypesValidate *validator.Validate

func init() {
	bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(bodyTypesValidate)
}

type CreateUserBody struct {
	// ID Auto-generated user ID. This is readOnly AND required.
	// - In request bodies (POST, PATCH): should be optional (pointer with omitempty)
	// - In responses (GET): should be required (non-pointer)
	ID *string `json:"id,omitempty"`

	// Name User's full name (regular required field)
	Name string `json:"name" validate:"required"`

	// Email User's email address (regular required field)
	Email runtime.Email `json:"email" validate:"required"`

	// Password User's password. This is writeOnly AND required.
	// - In request bodies (POST, PATCH): should be required
	// - In responses (GET): should not be present
	Password string `json:"password" validate:"required"`

	// Bio Optional user biography (not required, not readOnly/writeOnly)
	Bio *string `json:"bio,omitempty"`

	// CreatedAt Auto-generated creation timestamp. This is readOnly AND required.
	// - In request bodies: should be optional (pointer with omitempty)
	// - In responses: should be required (non-pointer)
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// UpdatedAt Auto-generated update timestamp. This is readOnly but NOT required.
	// - In request bodies: should be optional (pointer with omitempty)
	// - In responses: should be optional (pointer with omitempty)
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`

	// LastLogin Optional last login timestamp (readOnly but not required)
	LastLogin *time.Time `json:"lastLogin,omitempty"`
}

func (c CreateUserBody) Validate() error {
	var errors runtime.ValidationErrors
	if err := bodyTypesValidate.Var(c.Name, "required"); err != nil {
		errors = errors.Append("Name", err)
	}
	if v, ok := any(c.Email).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Email", err)
		}
	}
	if err := bodyTypesValidate.Var(c.Password, "required"); err != nil {
		errors = errors.Append("Password", err)
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type UpdateUserBody struct {
	// ID Auto-generated user ID. This is readOnly AND required.
	// - In request bodies (POST, PATCH): should be optional (pointer with omitempty)
	// - In responses (GET): should be required (non-pointer)
	ID *string `json:"id,omitempty"`

	// Name User's full name (regular required field)
	Name string `json:"name" validate:"required"`

	// Email User's email address (regular required field)
	Email runtime.Email `json:"email" validate:"required"`

	// Password User's password. This is writeOnly AND required.
	// - In request bodies (POST, PATCH): should be required
	// - In responses (GET): should not be present
	Password string `json:"password" validate:"required"`

	// Bio Optional user biography (not required, not readOnly/writeOnly)
	Bio *string `json:"bio,omitempty"`

	// CreatedAt Auto-generated creation timestamp. This is readOnly AND required.
	// - In request bodies: should be optional (pointer with omitempty)
	// - In responses: should be required (non-pointer)
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// UpdatedAt Auto-generated update timestamp. This is readOnly but NOT required.
	// - In request bodies: should be optional (pointer with omitempty)
	// - In responses: should be optional (pointer with omitempty)
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`

	// LastLogin Optional last login timestamp (readOnly but not required)
	LastLogin *time.Time `json:"lastLogin,omitempty"`
}

func (u UpdateUserBody) Validate() error {
	var errors runtime.ValidationErrors
	if err := bodyTypesValidate.Var(u.Name, "required"); err != nil {
		errors = errors.Append("Name", err)
	}
	if v, ok := any(u.Email).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Email", err)
		}
	}
	if err := bodyTypesValidate.Var(u.Password, "required"); err != nil {
		errors = errors.Append("Password", err)
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type CreateUserResponse struct {
	// ID Auto-generated user ID. This is readOnly AND required.
	// - In request bodies (POST, PATCH): should be optional (pointer with omitempty)
	// - In responses (GET): should be required (non-pointer)
	ID string `json:"id" validate:"required"`

	// Name User's full name (regular required field)
	Name string `json:"name" validate:"required"`

	// Email User's email address (regular required field)
	Email runtime.Email `json:"email" validate:"required"`

	// Password User's password. This is writeOnly AND required.
	// - In request bodies (POST, PATCH): should be required
	// - In responses (GET): should not be present
	Password string `json:"password" validate:"required"`

	// Bio Optional user biography (not required, not readOnly/writeOnly)
	Bio *string `json:"bio,omitempty"`

	// CreatedAt Auto-generated creation timestamp. This is readOnly AND required.
	// - In request bodies: should be optional (pointer with omitempty)
	// - In responses: should be required (non-pointer)
	CreatedAt time.Time `json:"createdAt" validate:"required"`

	// UpdatedAt Auto-generated update timestamp. This is readOnly but NOT required.
	// - In request bodies: should be optional (pointer with omitempty)
	// - In responses: should be optional (pointer with omitempty)
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`

	// LastLogin Optional last login timestamp (readOnly but not required)
	LastLogin *time.Time `json:"lastLogin,omitempty"`
}

type ListUsersResponse []User

type GetUserResponse struct {
	// ID Auto-generated user ID. This is readOnly AND required.
	// - In request bodies (POST, PATCH): should be optional (pointer with omitempty)
	// - In responses (GET): should be required (non-pointer)
	ID string `json:"id" validate:"required"`

	// Name User's full name (regular required field)
	Name string `json:"name" validate:"required"`

	// Email User's email address (regular required field)
	Email runtime.Email `json:"email" validate:"required"`

	// Password User's password. This is writeOnly AND required.
	// - In request bodies (POST, PATCH): should be required
	// - In responses (GET): should not be present
	Password string `json:"password" validate:"required"`

	// Bio Optional user biography (not required, not readOnly/writeOnly)
	Bio *string `json:"bio,omitempty"`

	// CreatedAt Auto-generated creation timestamp. This is readOnly AND required.
	// - In request bodies: should be optional (pointer with omitempty)
	// - In responses: should be required (non-pointer)
	CreatedAt time.Time `json:"createdAt" validate:"required"`

	// UpdatedAt Auto-generated update timestamp. This is readOnly but NOT required.
	// - In request bodies: should be optional (pointer with omitempty)
	// - In responses: should be optional (pointer with omitempty)
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`

	// LastLogin Optional last login timestamp (readOnly but not required)
	LastLogin *time.Time `json:"lastLogin,omitempty"`
}

type UpdateUserResponse struct {
	// ID Auto-generated user ID. This is readOnly AND required.
	// - In request bodies (POST, PATCH): should be optional (pointer with omitempty)
	// - In responses (GET): should be required (non-pointer)
	ID string `json:"id" validate:"required"`

	// Name User's full name (regular required field)
	Name string `json:"name" validate:"required"`

	// Email User's email address (regular required field)
	Email runtime.Email `json:"email" validate:"required"`

	// Password User's password. This is writeOnly AND required.
	// - In request bodies (POST, PATCH): should be required
	// - In responses (GET): should not be present
	Password string `json:"password" validate:"required"`

	// Bio Optional user biography (not required, not readOnly/writeOnly)
	Bio *string `json:"bio,omitempty"`

	// CreatedAt Auto-generated creation timestamp. This is readOnly AND required.
	// - In request bodies: should be optional (pointer with omitempty)
	// - In responses: should be required (non-pointer)
	CreatedAt time.Time `json:"createdAt" validate:"required"`

	// UpdatedAt Auto-generated update timestamp. This is readOnly but NOT required.
	// - In request bodies: should be optional (pointer with omitempty)
	// - In responses: should be optional (pointer with omitempty)
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`

	// LastLogin Optional last login timestamp (readOnly but not required)
	LastLogin *time.Time `json:"lastLogin,omitempty"`
}

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type User struct {
	// ID Auto-generated user ID. This is readOnly AND required.
	// - In request bodies (POST, PATCH): should be optional (pointer with omitempty)
	// - In responses (GET): should be required (non-pointer)
	ID string `json:"id" validate:"required"`

	// Name User's full name (regular required field)
	Name string `json:"name" validate:"required"`

	// Email User's email address (regular required field)
	Email runtime.Email `json:"email" validate:"required"`

	// Password User's password. This is writeOnly AND required.
	// - In request bodies (POST, PATCH): should be required
	// - In responses (GET): should not be present
	Password string `json:"password" validate:"required"`

	// Bio Optional user biography (not required, not readOnly/writeOnly)
	Bio *string `json:"bio,omitempty"`

	// CreatedAt Auto-generated creation timestamp. This is readOnly AND required.
	// - In request bodies: should be optional (pointer with omitempty)
	// - In responses: should be required (non-pointer)
	CreatedAt time.Time `json:"createdAt" validate:"required"`

	// UpdatedAt Auto-generated update timestamp. This is readOnly but NOT required.
	// - In request bodies: should be optional (pointer with omitempty)
	// - In responses: should be optional (pointer with omitempty)
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`

	// LastLogin Optional last login timestamp (readOnly but not required)
	LastLogin *time.Time `json:"lastLogin,omitempty"`
}

func (u User) Validate() error {
	var errors runtime.ValidationErrors
	if err := schemaTypesValidate.Var(u.ID, "required"); err != nil {
		errors = errors.Append("ID", err)
	}
	if err := schemaTypesValidate.Var(u.Name, "required"); err != nil {
		errors = errors.Append("Name", err)
	}
	if v, ok := any(u.Email).(runtime.Validator); ok {
		if err := v.Validate(); err != nil {
			errors = errors.Append("Email", err)
		}
	}
	if err := schemaTypesValidate.Var(u.Password, "required"); err != nil {
		errors = errors.Append("Password", err)
	}
	if err := schemaTypesValidate.Var(u.CreatedAt, "required"); err != nil {
		errors = errors.Append("CreatedAt", err)
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}
