openapi: "3.0.0"
info:
  version: 1.0.0
  title: additional-properties
components:
  schemas:
    items:
      type: array
      additionalProperties: true

    optional-items:
      additionalProperties:
        type: string
        nullable: true

    location:
      type: object
      additionalProperties: true
      nullable: true

    users:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/user'

    user:
      type: object
      properties:
        address:
          type: object

    pick-1:
      type: object
      nullable: true
      maximum: 5
      additionalProperties:
        oneOf:
          - type: string
          - type: number

    referenceWithRequiredExtra:
      type: object
      properties:
        index:
          $ref: '#/components/schemas/reference'
      additionalProperties:
        $ref: '#/components/schemas/reference'

    routeWithOptionalExtra:
      type: object
      properties:
        index:
          $ref: '#/components/schemas/route'
      additionalProperties:
        $ref: '#/components/schemas/route'

    route:
      type: string
      nullable: true

    reference:
      type: string
      nullable: false

    # Example with minProperties constraint
    configWithMinProps:
      type: object
      minProperties: 1
      additionalProperties:
        type: string

    # Example with maxProperties constraint
    configWithMaxProps:
      type: object
      maxProperties: 5
      additionalProperties:
        type: string

    # Example with both minProperties and maxProperties
    configWithBothProps:
      type: object
      minProperties: 2
      maxProperties: 10
      additionalProperties:
        type: integer

    # Example with required fields in additional properties value
    usersWithRequiredFields:
      type: object
      additionalProperties:
        type: object
        required:
          - name
          - email
        properties:
          name:
            type: string
          email:
            type: string
          age:
            type: integer

    # Example with array constraints
    arrayWithMinItems:
      type: array
      minItems: 1
      maxItems: 100
      items:
        type: string

    # Example with string length constraints (type alias)
    Username:
      type: string
      minLength: 3
      maxLength: 20

    # Example with string in object
    UserProfile:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 20

    # Example with string length constraints
    username:
      type: string
      minLength: 3
      maxLength: 20

    # Example with map of strings with length constraints
    tagsWithLength:
      type: object
      additionalProperties:
        type: string
        minLength: 1
        maxLength: 50

    # Example with map that has both item count and value length constraints
    tagsWithBothConstraints:
      type: object
      minProperties: 2
      maxProperties: 5
      additionalProperties:
        type: string
        minLength: 1
        maxLength: 50
