// Code generated by oapi-codegen. DO NOT EDIT.

package xoapicodegenonlyhonourgoname

import (
	"github.com/go-playground/validator/v10"
	"github.com/uptrace/oapi-codegen-dd/v3/pkg/runtime"
)

// TypeWithUnexportedField A struct will be output where one of the fields is not exported
type TypeWithUnexportedField struct {
	Name              *string `json:"name,omitempty"`
	accountIdentifier *string `json:"-"`
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
