// Code generated by oapi-codegen. DO NOT EDIT.

package xoapicodegenonlyhonourgoname

import (
	"github.com/go-playground/validator/v10"
)

var schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())

// TypeWithUnexportedField A struct will be output where one of the fields is not exported
type TypeWithUnexportedField struct {
	Name              *string `json:"name,omitempty"`
	accountIdentifier *string `json:"-"`
}

func (t TypeWithUnexportedField) Validate() error {
	return schemaTypesValidate.Struct(t)
}
