// Code generated by oapi-codegen. DO NOT EDIT.

package xoapicodegenonlyhonourgoname

// TypeWithUnexportedField A struct will be output where one of the fields is not exported
type TypeWithUnexportedField struct {
	Name              *string `json:"name,omitempty"`
	accountIdentifier *string `json:"-"`
}
