// Code generated by oapi-codegen. DO NOT EDIT.

package gen

import (
	"fmt"

	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

// ProductName The PayPal product for which the customer is onboarded.
type ProductName string

const (
	ProductNameADVANCEDVAULTING ProductName = "ADVANCED_VAULTING"
	ProductNameEXPRESSCHECKOUT  ProductName = "EXPRESS_CHECKOUT"
	ProductNamePAYMENTMETHODS   ProductName = "PAYMENT_METHODS"
	ProductNamePPCP             ProductName = "PPCP"
	ProductNamePPPLUS           ProductName = "PPPLUS"
	ProductNameWPPRO            ProductName = "WP_PRO"
)

// Validate checks if the ProductName value is valid
func (p ProductName) Validate() error {
	switch p {
	case ProductNameADVANCEDVAULTING, ProductNameEXPRESSCHECKOUT, ProductNamePAYMENTMETHODS, ProductNamePPCP, ProductNamePPPLUS, ProductNameWPPRO:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ProductName value, got: %v", p))
	}
}

// ProductName1 The name of the product.
type ProductName1 string

const (
	ProductName1ADVANCEDVAULTING          ProductName1 = "ADVANCED_VAULTING"
	ProductName1BILLMELATER               ProductName1 = "BILL_ME_LATER"
	ProductName1EBAYCHECKOUT              ProductName1 = "EBAY_CHECKOUT"
	ProductName1EMAILPAYMENTS             ProductName1 = "EMAIL_PAYMENTS"
	ProductName1ENHANCEDRECURRINGPAYMENTS ProductName1 = "ENHANCED_RECURRING_PAYMENTS"
	ProductName1EXPRESSCHECKOUT           ProductName1 = "EXPRESS_CHECKOUT"
	ProductName1HOSTEDSOLESOLUTION        ProductName1 = "HOSTED_SOLE_SOLUTION"
	ProductName1MASSPAYMENT               ProductName1 = "MASS_PAYMENT"
	ProductName1MOBILEEXPRESSCHECKOUT     ProductName1 = "MOBILE_EXPRESS_CHECKOUT"
	ProductName1MOBILEINSTORE             ProductName1 = "MOBILE_IN_STORE"
	ProductName1MOBILEPAYMENTACCEPTANCE   ProductName1 = "MOBILE_PAYMENT_ACCEPTANCE"
	ProductName1MOBILEPAYPALSTANDARD      ProductName1 = "MOBILE_PAYPAL_STANDARD"
	ProductName1PAYFLOWLINK               ProductName1 = "PAYFLOW_LINK"
	ProductName1PAYFLOWPRO                ProductName1 = "PAYFLOW_PRO"
	ProductName1PAYMENTMETHODS            ProductName1 = "PAYMENT_METHODS"
	ProductName1PAYPALADVANCED            ProductName1 = "PAYPAL_ADVANCED"
	ProductName1PAYPALHERE                ProductName1 = "PAYPAL_HERE"
	ProductName1PAYPALPRO                 ProductName1 = "PAYPAL_PRO"
	ProductName1PAYPALSTANDARD            ProductName1 = "PAYPAL_STANDARD"
	ProductName1PPCPCUSTOM                ProductName1 = "PPCP_CUSTOM"
	ProductName1PPCPSTANDARD              ProductName1 = "PPCP_STANDARD"
	ProductName1VIRTUALTERMINAL           ProductName1 = "VIRTUAL_TERMINAL"
	ProductName1WEBSITEPAYMENTSPRO20      ProductName1 = "WEBSITE_PAYMENTS_PRO_2_0"
	ProductName1WEBSITEPAYMENTSPRO30      ProductName1 = "WEBSITE_PAYMENTS_PRO_3_0"
	ProductName1WEBSITEPAYMENTSSTANDARD   ProductName1 = "WEBSITE_PAYMENTS_STANDARD"
)

// Validate checks if the ProductName1 value is valid
func (p ProductName1) Validate() error {
	switch p {
	case ProductName1ADVANCEDVAULTING, ProductName1BILLMELATER, ProductName1EBAYCHECKOUT, ProductName1EMAILPAYMENTS, ProductName1ENHANCEDRECURRINGPAYMENTS, ProductName1EXPRESSCHECKOUT, ProductName1HOSTEDSOLESOLUTION, ProductName1MASSPAYMENT, ProductName1MOBILEEXPRESSCHECKOUT, ProductName1MOBILEINSTORE, ProductName1MOBILEPAYMENTACCEPTANCE, ProductName1MOBILEPAYPALSTANDARD, ProductName1PAYFLOWLINK, ProductName1PAYFLOWPRO, ProductName1PAYMENTMETHODS, ProductName1PAYPALADVANCED, ProductName1PAYPALHERE, ProductName1PAYPALPRO, ProductName1PAYPALSTANDARD, ProductName1PPCPCUSTOM, ProductName1PPCPSTANDARD, ProductName1VIRTUALTERMINAL, ProductName1WEBSITEPAYMENTSPRO20, ProductName1WEBSITEPAYMENTSPRO30, ProductName1WEBSITEPAYMENTSSTANDARD:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ProductName1 value, got: %v", p))
	}
}

type ProductStatus string

const (
	ACTIVE   ProductStatus = "ACTIVE"
	INACTIVE ProductStatus = "INACTIVE"
	PENDING  ProductStatus = "PENDING"
)

// Validate checks if the ProductStatus value is valid
func (p ProductStatus) Validate() error {
	switch p {
	case ACTIVE, INACTIVE, PENDING:
		return nil
	default:
		return runtime.NewValidationErrorsFromString("Enum", fmt.Sprintf("must be a valid ProductStatus value, got: %v", p))
	}
}

type GetReferralsResponse struct {
	Products []ProductName `json:"products,omitempty"`
}

type GetMerchantsResponse struct {
	Products []Product `json:"products,omitempty"`
}

type Product struct {
	// Name The name of the product.
	Name   *ProductName1  `json:"name,omitempty"`
	Status *ProductStatus `json:"status,omitempty"`
}

func (p Product) Validate() error {
	var errors runtime.ValidationErrors
	if p.Name != nil {
		if v, ok := any(p.Name).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Name", err)
			}
		}
	}
	if p.Status != nil {
		if v, ok := any(p.Status).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Status", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

var typesValidator *validator.Validate

func init() {
	typesValidator = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(typesValidator)
}
