// Code generated by oapi-codegen. DO NOT EDIT.

package xgojsonignore

type Client struct {
	Name         string `json:"name" validate:"required"`
	ComplexField *struct {
		Name        *string `json:"name,omitempty"`
		AccountName *string `json:"accountName,omitempty"`
	} `json:"complexField,omitempty"`
}

type ClientWithExtension struct {
	Name         string `json:"name" validate:"required"`
	ComplexField *struct {
		Name        *string `json:"name,omitempty"`
		AccountName *string `json:"accountName,omitempty"`
	} `json:"-"`
}
