// Code generated by oapi-codegen. DO NOT EDIT.

package example1

import (
	"github.com/go-playground/validator/v10"
)

var headerTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type GetClientHeaders struct {
	MerchantSerialNumber MSN `json:"Merchant-Serial-Number" validate:"required,max=7,min=4"`
}

type UpdateClientHeaders struct {
	MerchantSerialNumber MSN `json:"Merchant-Serial-Number" validate:"required,max=7,min=4"`
}

type MSN = string
