// Code generated by oapi-codegen. DO NOT EDIT.

package example1

import (
	"github.com/go-playground/validator/v10"
)

var bodyTypesValidate = validator.New(validator.WithRequiredStructEnabled())

type UpdateClientBody = ClientType
