// Code generated by oapi-codegen. DO NOT EDIT.

package example1

type GetClientResponse struct {
	Name string                 `json:"name" validate:"required"`
	Type *GetClientResponseType `json:"type,omitempty"`
}

type GetClientErrorResponse struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (r GetClientErrorResponse) Error() string {
	res0 := r.Message
	if res0 == nil {
		return "unknown error"
	}
	res1 := *res0
	return res1
}

type UpdateClientErrorResponseJSON struct {
	Code    *ErrorCode `json:"code,omitempty"`
	Message *string    `json:"message,omitempty"`
}

func (r UpdateClientErrorResponseJSON) Error() string {
	res0 := r.Code
	if res0 == nil {
		return "unknown error"
	}
	res1 := *res0
	return res1
}
