// Code generated by oapi-codegen. DO NOT EDIT.

package example1

type GetClientResponse struct {
	Name string                 `json:"name" validate:"required"`
	Type *GetClientResponseType `json:"type,omitempty"`
}

type GetClientErrorResponse = Error

type UpdateClientErrorResponse struct {
	Code string `json:"code" validate:"required"`
}

func (r UpdateClientErrorResponse) Error() string {
	res0 := r.Code
	return res0
}
