// Code generated by oapi-codegen. DO NOT EDIT.

package example1

import (
	"github.com/doordash/oapi-codegen-dd/v3/pkg/runtime"
	"github.com/go-playground/validator/v10"
)

var schemaTypesValidate *validator.Validate

func init() {
	schemaTypesValidate = validator.New(validator.WithRequiredStructEnabled())
	runtime.RegisterCustomTypeFunc(schemaTypesValidate)
}

type ClientType struct {
	Name string          `json:"name" validate:"required"`
	Type *ClientTypeType `json:"type,omitempty"`
}

func (c ClientType) Validate() error {
	var errors runtime.ValidationErrors
	if err := schemaTypesValidate.Var(c.Name, "required"); err != nil {
		errors = errors.Append("Name", err)
	}
	if c.Type != nil {
		if v, ok := any(c.Type).(runtime.Validator); ok {
			if err := v.Validate(); err != nil {
				errors = errors.Append("Type", err)
			}
		}
	}
	if len(errors) == 0 {
		return nil
	}
	return errors
}

type Error struct {
	Code    *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

type UpdateClientErrorResponse struct {
	Code    *ErrorCode `json:"code,omitempty"`
	Message *string    `json:"message,omitempty"`
}

type ErrorCode = string
